services:
    #integration
    oro_wirecard.integation.wirecard_seamless.channel:
        class: 'Oro\Bundle\WirecardBundle\Integration\WirecardSeamlessChannelType'
        tags:
            - { name: oro_integration.channel, type: wirecard_seamless }

    oro_wirecard.integration.wirecard_seamless.transport:
        class: 'Oro\Bundle\WirecardBundle\Integration\WirecardSeamlessTransport'
        tags:
            - { name: oro_integration.transport, type: wirecard_seamless, channel_type: wirecard_seamless }

    oro_wirecard.provider.payment_transaction:
        class: 'Oro\Bundle\WirecardBundle\Provider\PaymentTransactionProvider'
        parent: oro_payment.provider.payment_transaction
        public: false

    oro_wirecard.request.payment_method_param_converter:
        class: 'Oro\Bundle\WirecardBundle\Request\PaymentMethodParamConverter'
        public: false
        arguments:
            - '@oro_payment.payment_method.composite_provider'
        tags:
            - { name: request.param_converter, priority: -2, converter: payment_method_param_converter }
