services:
    #integration
    oro_wirecard.integation.wirecard_seamless.channel:
        class: 'Oro\Bundle\WirecardBundle\Integration\WirecardSeamlessChannelType'
        tags:
            - { name: oro_integration.channel, type: wirecard_seamless }

    oro_wirecard.integration.wirecard_seamless.transport:
        class: 'Oro\Bundle\WirecardBundle\Integration\WirecardSeamlessTransport'
        tags:
            - { name: oro_integration.transport, type: wirecard_seamless, channel_type: wirecard_seamless }

    oro_wirecard.provider.payment_transaction:
        class: 'Oro\Bundle\WirecardBundle\Provider\PaymentTransactionProvider'
        parent: oro_payment.provider.payment_transaction
        # This service marked as public (origin private) for compatibility with Symfony 4. All dependencies must be refactored after BAP-17037
        public: true

    oro_wirecard.request.payment_method_param_converter:
        class: 'Oro\Bundle\WirecardBundle\Request\PaymentMethodParamConverter'
        public: false
        arguments:
            - '@oro_payment.payment_method.composite_provider'
        tags:
            - { name: request.param_converter, priority: -2, converter: payment_method_param_converter }

    oro_wirecard.validator.constraints.methods_configs_rule:
        class: Oro\Bundle\WirecardBundle\Validator\Constraints\PaymentMethodsConfigsRuleConstraintValidator
        arguments:
            - '@oro_wirecard.method.config.provider.wirecard_seamless.sepa_direct_debit'
        tags:
            - { name: validator.constraint_validator }

    oro_wirecard.options_provider.options:
        class: 'Oro\Bundle\WirecardBundle\OptionsProvider\OptionsProvider'
        public: false
        arguments:
            - '@oro_payment.provider.payment_order_shipping_address_options'
