Oro\Bundle\WirecardBundle\Entity\WirecardSeamlessSettings:
    properties:
        creditCardLabels:
            - NotBlank: ~
        creditCardShortLabels:
            - NotBlank: ~
        paypalLabels:
            - NotBlank: ~
        paypalShortLabels:
            - NotBlank: ~
        sepaLabels:
            - NotBlank: ~
        sepaShortLabels:
            - NotBlank: ~
        customerId:
            - NotBlank: ~
            - Valid: ~
        secret:
            - NotBlank: ~
            - Length:
                min: 7

Oro\Bundle\PaymentBundle\Entity\PaymentMethodsConfigsRule:
    constraints:
        - Oro\Bundle\WirecardBundle\Validator\Constraints\PaymentMethodsConfigsRuleConstraint: ~
