dynamic-imports:
    orowirecard:
        - orowirecard/js/app/components/input-wirecard-seamless
        - orowirecard/js/app/components/input-wirecard-seamless-credit-card
        - orowirecard/js/app/components/input-wirecard-seamless-sepa-direct-debit
        - orowirecard/js/app/components/wirecard-seamless-component
        - orowirecard/js/validator/sepa-bic
        - orowirecard/js/validator/sepa-iban
