config:
    paths:
        'orowirecard/js/app/components/input-wirecard-seamless-wirecard': 'bundles/orowirecard/js/app/components/input-wirecard-seamless.js'
        'orowirecard/js/app/components/input-wirecard-seamless-credit-card': 'bundles/orowirecard/js/app/components/input-wirecard-seamless-credit-card.js'
        'orowirecard/js/app/components/input-wirecard-seamless-sepa-direct-debit': 'bundles/orowirecard/js/app/components/input-wirecard-seamless-sepa-direct-debit.js'
        'orowirecard/js/app/components/wirecard-seamless-component': 'bundles/orowirecard/js/app/components/wirecard-seamless-component.js'
        'orowirecard/js/validator/sepa-iban': 'bundles/orowirecard/js/validator/sepa-iban.js'
        'orowirecard/js/validator/sepa-bic': 'bundles/orowirecard/js/validator/sepa-bic.js'
#        'orowirecard/js/app/components/input-wirecard-seamless-wirecard-datastorage-mock': 'bundles/orowirecard/js/stubs/wirecard-data-storage-mock.js'
